all:prog2 p2crypt dirlist p2archive p2unarchive

prog2 : prog2.c
	gcc -Wall -g prog2.c -o prog2

p2crypt : p2crypt.c
	gcc -Wall -g p2crypt.c -o p2crypt

dirlist : dirlist.c
	gcc -Wall -g dirlist.c -o dirlist

p2archive : p2archive.c
	gcc -Wall -g p2archive.c -o p2archive

p2unarchive : p2unarchive.c
	gcc -Wall -g p2unarchive.c -o p2unarchive
